<?php
add_action('woocommerce_loaded', function () {

    if ( ! class_exists( 'WC_Session_Handler' ) ) {
        return;
    }
    if ( ! class_exists( 'NSI_Session_Handler' ) ) {
	class NSI_Session_Handler extends WC_Session_Handler  {

        /**
         * Setup cookie and customer ID.
         */
        public function init_session_cookie() {
            $cookie = $this->get_session_cookie();

            if ( $cookie ) {
                // Customer ID will be an MD5 hash id this is a guest session.
                $this->_customer_id        = $cookie[0];
                $this->_session_expiration = $cookie[1];
                $this->_session_expiring   = $cookie[2];
                $this->_has_cookie         = true;
                $this->_data               = $this->get_session_data();

                if ( ! $this->is_session_cookie_valid() ) {
                    $this->destroy_session();
                    $this->set_session_expiration();
                }

                $id = get_current_user_id();
                $id = $this->get_switched_customer_unique_id($id);

                // If the user logs in, update session.
                if ( is_user_logged_in() && strval( $id ) !== $this->_customer_id ) {
                    $guest_session_id   = $this->_customer_id;
                    $this->_customer_id = strval( $id );
                    $this->_dirty       = true;
                    $this->save_data( $guest_session_id );
                    $this->set_customer_session_cookie( true );

                    /**
                     * Fires after a customer has logged in, and their guest session id has been
                     * deleted with its data migrated to a customer id.
                     *
                     * This hook gives extensions the chance to connect the old session id to the
                     * customer id, if the key is being used externally.
                     *
                     * @since 8.8.0
                     *
                     * @param string $guest_session_id The former session ID, as generated by `::generate_customer_id()`.
                     * @param int    $customer_id      The Customer ID that the former session was converted to.
                     */
                    do_action( 'woocommerce_guest_session_to_user_id', $guest_session_id, $this->_customer_id );
                }

                // Update session if its close to expiring.
                if ( time() > $this->_session_expiring ) {
                    $this->set_session_expiration();
                    $this->update_session_timestamp( $this->_customer_id, $this->_session_expiration );
                }
            } else {
                $this->set_session_expiration();
                $this->_customer_id = $this->generate_customer_id();
                $this->_data        = $this->get_session_data();
            }
        }

        /**
         * Checks if session cookie is expired, or belongs to a logged out user.
         *
         * @return bool Whether session cookie is valid.
         */
        private function is_session_cookie_valid() {
            // If session is expired, session cookie is invalid.
            if ( time() > $this->_session_expiration ) {
                return false;
            }

            // If user has logged out, session cookie is invalid.
            if ( ! is_user_logged_in() && ! $this->is_customer_guest( $this->_customer_id ) ) {
                return false;
            }

            // Session from a different user is not valid. (Although from a guest user will be valid).
            if ( is_user_logged_in() && ! $this->is_customer_guest( $this->_customer_id ) && strval( get_current_user_id() ) !== $this->_customer_id ) {
                return false;
            }

            return true;
        }

        /**
         * Checks if this is an auto-generated customer ID.
         *
         * @param string|int $customer_id Customer ID to check.
         *
         * @return bool Whether customer ID is randomly generated.
         */
        private function is_customer_guest( $customer_id ) {
            $customer_id = strval( $customer_id );

            if ( empty( $customer_id ) ) {
                return true;
            }

            if ( 't_' === substr( $customer_id, 0, 2 ) ) {
                return true;
            }

            /**
             * Legacy checks. This is to handle sessions that were created from a previous release.
             * Maybe we can get rid of them after a few releases.
             */

            // Almost all random $customer_ids will have some letters in it, while all actual ids will be integers.
            if ( strval( (int) $customer_id ) !== $customer_id ) {
                return true;
            }

            // Performance hack to potentially save a DB query, when same user as $customer_id is logged in.
            if ( is_user_logged_in() && strval( get_current_user_id() ) === $customer_id ) {
                return false;
            } else {
                $customer = new WC_Customer( $customer_id );

                if ( 0 === $customer->get_id() ) {
                    return true;
                }
            }

            return false;
        }

        public function get_customer_id() {
            $id = parent::get_customer_id();
            return $this->get_switched_customer_unique_id($id);
        }

        public function generate_customer_id() {
            $id = parent::generate_customer_id();
            return $this->get_switched_customer_unique_id($id);
        }

        public function get_switched_customer_unique_id($id) {
            $admin_id = isset($_COOKIE['sac_admin_id']) ? $_COOKIE['sac_admin_id'] : 0;
            if ($id != $admin_id && $admin_id != 0) {
                $id = $id . '_' . $admin_id;
            }
            return $id;
        }

    }
    }

    add_filter('woocommerce_session_handler', function () {
        return 'NSI_Session_Handler';
    });
});
